name: hello-world
on: push
jobs:
  echo-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hello, World!"
  echo-goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: Success
        run: |
         echo "I will fail"
          exit 0
      - name: Say Goodbye
        run: echo "Goodbye, World!"
      

  