name: 02-workflow-events
on: push
jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: Show the trigger
              run: echo  "This hi workflow was triggered by a ${{github.event_name}} event."
                       