name: 02-workflow-events
on:
 push:
 pull_request:
 schedule:
   - cron: '1 * * * *'
 workflow_dispatch:
jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: Show the trigger
              run: echo  "This workflow was triggered by a ${{github.event_name}} event."
                       