name: 02-workflow-events
on:
 push:
 pull_request:
 schedule:
   - cron: '*/1 * * * *'
jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: Show the trigger
              run: echo  "This hi workflow was triggered by a ${{github.event_name}} event."
                       