name: Manual Deployment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - production
      version:
        description: 'Docker image tag to deploy (default: latest)'
        required: false
        default: 'latest'
      rollback:
        description: 'Perform rollback instead of deployment'
        required: false
        default: false
        type: boolean

env:
  DOTNET_VERSION: '8.0.x'
  DOCKER_IMAGE_NAME: 'contact-app-api'
  REGISTRY: ghcr.io

jobs:
  manual-deploy:
    name: Manual Deploy/Rollback
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Log deployment details
      run: |
        echo "Environment: ${{ github.event.inputs.environment }}"
        echo "Version: ${{ github.event.inputs.version }}"
        echo "Rollback: ${{ github.event.inputs.rollback }}"
        echo "Image: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.DOCKER_IMAGE_NAME }}:${{ github.event.inputs.version }}"
        
    - name: Perform Rollback
      if: ${{ github.event.inputs.rollback == 'true' }}
      run: |
        echo "Performing rollback to previous version..."
        # Add your rollback commands here
        # Example: Deploy previous stable version, restore database backup, etc.
        
    - name: Perform Deployment
      if: ${{ github.event.inputs.rollback != 'true' }}
      run: |
        echo "Deploying version ${{ github.event.inputs.version }} to ${{ github.event.inputs.environment }}..."
        # Add your deployment commands here
        
    - name: Health Check
      run: |
        echo "Running health checks..."
        # Add your health check commands here
        
    - name: Notification
      if: always()
      run: |
        echo "Manual operation completed with status: ${{ job.status }}"
        echo "Environment: ${{ github.event.inputs.environment }}"
        echo "Action: ${{ github.event.inputs.rollback == 'true' && 'Rollback' || 'Deployment' }}"